# Change these first
owner: knilessew # Your GitHub organization or username, where this repository lives
repo: upptimeKnilessew # The name of this repository

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "*/60 * * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

delay: 2000 # 2 seconds

sites:
  - name: ThuisIP
    check: "tcp-ping"
    url: 217.27.229.52
    port: 443
  - name: Alpacamundo PRD
    url: https://alpacamundo.eu
  - name: Alpacamundo PRD API Healthcheck
    url: https://api.alpacamundo.eu/api/health
    __dangerous__body_down_if_text_missing: "Healthy"
  - name: Alpacamundo PRD DB Check
    url: https://api.alpacamundo.eu/api/alpacas
    __dangerous__body_down_if_text_missing: '"breed":"Huacaya"' 
  - name: Alpacamundo TST
    url: https://tst.alpacamundo.eu
  - name: Alpacamundo TST API Healthcheck
    url: https://api-tst.alpacamundo.eu/api/health
    __dangerous__body_down_if_text_missing: "Healthy"
  - name: Alpacamundo TST DB Check
    url: https://api-tst.alpacamundo.eu/api/alpacas
    __dangerous__body_down_if_text_missing: '"breed":"Huacaya"' 
  - name: Alpacamundo TST API Swagger
    url: https://api-tst.alpacamundo.eu/swagger/index.html
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptimeKnilessew
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UpptimeKnilessew
  introTitle: "**Upptime** for knilessew monitoring"
  introMessage: "introMessage: will come here"
  navbar:
    - title: Status
      href: /upptimeKnilessew
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
