# Change these first
owner: knilessew # Your GitHub organization or username, where this repository lives
repo: upptimeKnilessew # The name of this repository

sites:
  - name: ThuisIP
    url: 217.27.229.52
  - name: Alpacamundo PRD
    url: https://alpacamundo.eu
  - name: Alpacamundo API Healthcheck
    url: https://api.alpacamundo.eu/api/health
    __dangerous__body_down_if_text_missing: "Healthy"
  - name: Alpacamundo DB Check
    url: https://api.alpacamundo.eu/api/alpacas
    __dangerous__body_down_if_text_missing: "Healthy" 

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /upptimeKnilessew
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: UpptimeKnilessew
  introTitle: "**Upptime** for knilessew monitoring"
  introMessage: "introMessage: will come here"
  navbar:
    - title: Status
      href: /upptimeKnilessew
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
