name: Daily Backup

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 1 * * *'  # 03:00 Dutch time (01:00 UTC)
  workflow_dispatch:      # manual trigger from Actions tab

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 1  # We only need latest commit

    - name: Create archive of repository
      run: zip -r repo-backup.zip . =x "*.git*"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: repo-backup
        path: repo-backup.zip
        retention-days: 7  # Keep backups for 7 days